namespace NHLPlayerStatistics.Models;


//Autogenerated from NHL_API JSON response using "Paste Special" tool from Visual Studio


public class NHLPlayerDTO
{
    public string copyright { get; set; }
    public Stat[] stats { get; set; }
}

public class Stat
{
    public Type type { get; set; }
    public Split[] splits { get; set; }
}

public class Type
{
    public string displayName { get; set; }
    public object gameType { get; set; }
}

public class Split
{
    public string season { get; set; }
    public Stat1 stat { get; set; }
    public Team team { get; set; }
    public League league { get; set; }
    public int sequenceNumber { get; set; }
}

public class Stat1
{
    public int assists { get; set; }
    public int goals { get; set; }
    public int pim { get; set; }
    public int games { get; set; }
    public string penaltyMinutes { get; set; }
    public int plusMinus { get; set; }
    public int points { get; set; }
    public string timeOnIce { get; set; }
    public string powerPlayTimeOnIce { get; set; }
    public string evenTimeOnIce { get; set; }
    public float faceOffPct { get; set; }
    public string shortHandedTimeOnIce { get; set; }
    public int shifts { get; set; }
    public int shots { get; set; }
    public int hits { get; set; }
    public int powerPlayGoals { get; set; }
    public int powerPlayPoints { get; set; }
    public float shotPct { get; set; }
    public int gameWinningGoals { get; set; }
    public int overTimeGoals { get; set; }
    public int shortHandedGoals { get; set; }
    public int shortHandedPoints { get; set; }
    public int blocked { get; set; }
}

public class Team
{
    public string name { get; set; }
    public string link { get; set; }
    public int id { get; set; }
}

public class League
{
    public string name { get; set; }
    public string link { get; set; }
    public int id { get; set; }
}
